// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: management/migration.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRegisterMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
}

func (x *AuthRegisterMigrationRequest) Reset() {
	*x = AuthRegisterMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRegisterMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterMigrationRequest) ProtoMessage() {}

func (x *AuthRegisterMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterMigrationRequest.ProtoReflect.Descriptor instead.
func (*AuthRegisterMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRegisterMigrationRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type AuthRegisterMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthRegisterMigrationResponse) Reset() {
	*x = AuthRegisterMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRegisterMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterMigrationResponse) ProtoMessage() {}

func (x *AuthRegisterMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterMigrationResponse.ProtoReflect.Descriptor instead.
func (*AuthRegisterMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{1}
}

type AuthFinishMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthFinishMigrationRequest) Reset() {
	*x = AuthFinishMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthFinishMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFinishMigrationRequest) ProtoMessage() {}

func (x *AuthFinishMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFinishMigrationRequest.ProtoReflect.Descriptor instead.
func (*AuthFinishMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{2}
}

type AuthFinishMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthFinishMigrationResponse) Reset() {
	*x = AuthFinishMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthFinishMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFinishMigrationResponse) ProtoMessage() {}

func (x *AuthFinishMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFinishMigrationResponse.ProtoReflect.Descriptor instead.
func (*AuthFinishMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{3}
}

type AuthRollbackMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthRollbackMigrationRequest) Reset() {
	*x = AuthRollbackMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRollbackMigrationRequest) ProtoMessage() {}

func (x *AuthRollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*AuthRollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{4}
}

type AuthRollbackMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthRollbackMigrationResponse) Reset() {
	*x = AuthRollbackMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRollbackMigrationResponse) ProtoMessage() {}

func (x *AuthRollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*AuthRollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{5}
}

type AuthGetMigrationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthGetMigrationStatusRequest) Reset() {
	*x = AuthGetMigrationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthGetMigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGetMigrationStatusRequest) ProtoMessage() {}

func (x *AuthGetMigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGetMigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*AuthGetMigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{6}
}

type AuthGetMigrationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *AuthGetMigrationStatusResponse) Reset() {
	*x = AuthGetMigrationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthGetMigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGetMigrationStatusResponse) ProtoMessage() {}

func (x *AuthGetMigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGetMigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*AuthGetMigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{7}
}

func (x *AuthGetMigrationStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_management_migration_proto protoreflect.FileDescriptor

var file_management_migration_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x1c, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73,
	0x22, 0x1f, 0x0a, 0x1d, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x75, 0x74, 0x68, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1d, 0x0a, 0x1b, 0x41, 0x75, 0x74, 0x68, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e,
	0x0a, 0x1c, 0x41, 0x75, 0x74, 0x68, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f,
	0x0a, 0x1d, 0x41, 0x75, 0x74, 0x68, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1f, 0x0a, 0x1d, 0x41, 0x75, 0x74, 0x68, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x34, 0x0a, 0x1e, 0x41, 0x75, 0x74, 0x68, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_management_migration_proto_rawDescOnce sync.Once
	file_management_migration_proto_rawDescData = file_management_migration_proto_rawDesc
)

func file_management_migration_proto_rawDescGZIP() []byte {
	file_management_migration_proto_rawDescOnce.Do(func() {
		file_management_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_management_migration_proto_rawDescData)
	})
	return file_management_migration_proto_rawDescData
}

var file_management_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_management_migration_proto_goTypes = []interface{}{
	(*AuthRegisterMigrationRequest)(nil),   // 0: management.AuthRegisterMigrationRequest
	(*AuthRegisterMigrationResponse)(nil),  // 1: management.AuthRegisterMigrationResponse
	(*AuthFinishMigrationRequest)(nil),     // 2: management.AuthFinishMigrationRequest
	(*AuthFinishMigrationResponse)(nil),    // 3: management.AuthFinishMigrationResponse
	(*AuthRollbackMigrationRequest)(nil),   // 4: management.AuthRollbackMigrationRequest
	(*AuthRollbackMigrationResponse)(nil),  // 5: management.AuthRollbackMigrationResponse
	(*AuthGetMigrationStatusRequest)(nil),  // 6: management.AuthGetMigrationStatusRequest
	(*AuthGetMigrationStatusResponse)(nil), // 7: management.AuthGetMigrationStatusResponse
}
var file_management_migration_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_management_migration_proto_init() }
func file_management_migration_proto_init() {
	if File_management_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_management_migration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRegisterMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRegisterMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthFinishMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthFinishMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRollbackMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRollbackMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthGetMigrationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthGetMigrationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_management_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_migration_proto_goTypes,
		DependencyIndexes: file_management_migration_proto_depIdxs,
		MessageInfos:      file_management_migration_proto_msgTypes,
	}.Build()
	File_management_migration_proto = out.File
	file_management_migration_proto_rawDesc = nil
	file_management_migration_proto_goTypes = nil
	file_management_migration_proto_depIdxs = nil
}
